apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hpe
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 5173
      targetPort: 5173
