apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: hpe
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "vault-root"
            - name: POSTGRES_PASSWORD
              value: "vault-root-secret"
            - name: POSTGRES_DB
              value: "hpedb"
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "vault-root", "-d", "hpedb"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "vault-root", "-d", "hpedb"]
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: init-sql
          configMap:
            name: postgres-init-sql
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
