apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: hpe
  labels:
    app: vault
data:
  vault.hcl: |
    storage "raft" {
      path    = "/vault/data"
      node_id = "hpe-node-1"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    api_addr     = "http://vault.hpe.svc.cluster.local:8200"
    cluster_addr = "http://vault.hpe.svc.cluster.local:8201"

    ui = true

    disable_mlock = true
